# Generated by Django 3.0.3 on 2020-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0002_auto_20200801_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
