# Generated by Django 3.0.3 on 2020-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
